[package]
name = "reiseblogg"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"

[dependencies]
axum = "0.8.9"
chrono = "0.4"
dotenvy = "0.15.7"
minijinja = { version = "2.22.0", features = ["loader"] }
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono"] }
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.0", features = ["compression-br", "compression-gzip", "fs", "set-header"] }
