services:
  postgres:
    image: postgres:18
    container_name: postgres-reiseblogg
    environment:
      POSTGRES_PASSWORD: db_secret
      POSTGRES_USER: db_user
      POSTGRES_DB: db_reiseblogg
    ports:
      - "5432:5432"
    volumes:
      - db_persistent_storage:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_persistent_storage:
  minio_data:
    external: true
